name: Release

on: 
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package -f pom.xml

      -   name: "Upload ARTIFACT 🚀"
          uses: "actions/upload-artifact@v3"
          with:
              name: "JAR-Files"
              path: "target/*.jar"

  release:
      name: Release
      runs-on: ubuntu-latest
      needs:
          - build
      steps:
          - name: "Download release artifact 🚀"
            uses: actions/download-artifact@v3
            with:
                name: JAR-Files

          -   name: "Create Github Release 🚀"
              uses: "softprops/action-gh-release@v1"
              with:
                  files: "*.jar"
                  generate_release_notes: true
                  fail_on_unmatched_files: true
